<a href="https://colab.research.google.com/github/autinn/machine-learning-a-z/blob/main/Data_preprocessing_tools.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing Tools

**bold text**## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt #get the pyplot module
import pandas as pd #import dataset

## Importing the dataset

In [ ]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values #row, column #inclusive zero #excluse upperbound
y = dataset.iloc[:, -1].values

#feature - variables containing information to predict what you predict (first column)
#dependent variable - what you want to predict (last column)

In [ ]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [ ]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

In [ ]:
#replace missing value with average salary

from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:,1:3]) #include all numerical columns #connect imputer to matrix look out missing vlue, compute the missing value
x[:,1:3] = imputer.transform(x[:,1:3]) #transform method to do the replacement of the values

In [ ]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

In [ ]:
#one hot encoding - 1 column in 3 columns (100 010 001)

### Encoding the Independent Variable

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [0])], remainder='passthrough')
#what trasnformer (kind of transfromation, what kind of encoding, index of the column)
#which columns don't include in the tranforming (skip)
#number of different country = how many bindary
#3 variables = 3 binary

x = np.array(ct.fit_transform(x))

In [ ]:
print (x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, random_state = 1)

In [ ]:
print(x_train)

[[1.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 37.0 67000.0]
 [0.0 1.0 0.0 50.0 83000.0]]


In [ ]:
print(x_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [ ]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [ ]:
print(y_test)

[0 1]


## Feature Scaling

In [ ]:
#standardisation - work most of the time
#normlisation - work for data that is normal distribution

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.fit_transform(x_test[:, 3:]) # test on a similar scale #apply same scale #get the same transofrmation


In [ ]:
print(x_train)

[[1.0 0.0 0.0 -0.8066752374797969 -0.7213204519277457]
 [1.0 0.0 0.0 0.6176450728387547 0.5817100418772143]
 [1.0 0.0 0.0 1.250676321869222 1.2332252887796944]
 [0.0 1.0 0.0 -1.597964298767881 -1.093614878729163]
 [0.0 0.0 1.0 -0.3319018007069463 -0.4420996318266829]
 [0.0 0.0 1.0 -0.20881239117324418 -1.2797620921298716]
 [1.0 0.0 0.0 -0.4901596129645631 0.11634200837544287]
 [0.0 1.0 0.0 1.5671919463844557 1.6055197155811116]]


In [ ]:
print(x_test)

[[0.0 1.0 0.0 1.0 1.0]
 [0.0 0.0 1.0 -1.0 -1.0]]
